### ISSUE TITLE
Newbie problems!

### ISSUE THREAD

**Issue by blitz-research** [GeoffCox/svelte-splitter#3]
Hi,

Sorry if this is a dumb question, but do I have to initialize the Split control somehow?

I've imported it into my svelte app using:

	import { Split } from '@geoffcox/svelte-splitter'

Is this even correct?

But when I try to add the super simple example from the docs, I get either an 'Error: Function called outside component initialization' exception, or more recently (as seen in chrome dev tools) this:

proxy.js?v=cd42939a:15 [HMR][Svelte] Unrecoverable HMR error in <Split>: next update will trigger a full reload
logError @ proxy.js?v=cd42939a:15
proxy.js?v=cd42939a:260 Uncaught TypeError: Cannot destructure property 'target' of 'options' as it is undefined.
    at new ProxyComponent (proxy.js?v=cd42939a:260:15)
    at new Proxy<Split> (proxy.js?v=cd42939a:349:11)
    at App.svelte:10:9
    at run (index.mjs:18:12)
    at Array.map (<anonymous>)
    at index.mjs:1932:58
    at flush (index.mjs:1173:17)
    at init (index.mjs:2027:9)
    at new App (App.svelte:11:12)
    at createProxiedComponent (svelte-hooks.js?v=cd42939a:341:9)

I've see references to having to create Components inside onMount in the <script> section so I tried adding this:

	import { onMount } from 'svelte'
	onMount(() => {
		new Split();
	});

And I think that made it sometimes work, but everything still seems to be super-unstable and I usually just get one of the first 2 ugly messages!

Any ideas?

**Comment by blitz-research** [comment]
OK, please ignore, came back to this morning, tried again but skipped the onMount stuff (as per demo src) and everything seems to be working fine for some reason.
